[build]
  base = "site"
  command = 'PATH="./node_modules/.bin:$PATH" hugo --gc --minify --cleanDestinationDir && PATH="./node_modules/.bin:$PATH" pagefind --site public'
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.163.3"
  HUGO_ENV = "production"
  HUGO_CACHEDIR = "/opt/build/cache/hugo_cache"

[context.deploy-preview]
  command = 'PATH="./node_modules/.bin:$PATH" hugo --gc --minify --cleanDestinationDir --baseURL "${DEPLOY_PRIME_URL}/" && PATH="./node_modules/.bin:$PATH" pagefind --site public'

[context.branch-deploy]
  command = 'PATH="./node_modules/.bin:$PATH" hugo --gc --minify --cleanDestinationDir --baseURL "${DEPLOY_PRIME_URL}/" && PATH="./node_modules/.bin:$PATH" pagefind --site public'
