baseURL = "https://bite-size-bios.com/"
locale = "en-US"
title = "Bite-Size Bios"
author = "Bite-Size Bios"
defaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "Blonde"

enableRobotsTXT = true
summaryLength = 30

[params]
  description = "Short, readable bios for curious people."
  mainSections = ["biographies"]
  base_color = "bg-bio-surface"
  paginator_pages = 5
  archive_dropdown = "false"
  tagsLimit = 20
  recentLimit = 5
  darkmode = "light"

  [params.post]
    thumbnail = true
    noimage = false
    thumbnail_height = "h-40 lg:h-44"
    thumbnail_width = "w-full lg:w-44"
    description = "130"

  [params.widgets]
    display = true
    mobile = true
    widgets = [
      # "archive",
      "category",
      "tags",
      "recent",
    ]

  [params.share]
    enable = true

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/abegong/bite-size-bios"
    icon = "github"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "biographies"
    name = "Biographies"
    url = "/biographies/"
    weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
